language: node_js
node_js:
- '6'
os:
- linux
git:
  depth: 3
branches:
  except:
  - /^feature/
before_install:
- openssl aes-256-cbc -K $encrypted_22aa0a535020_key -iv $encrypted_22aa0a535020_iv
  -in .env.yml.enc -out .env.yml -d
install:
- yarn global add serverless
- yarn global add serverless-plugin-chrome
- yarn install
script:
- npm run test
after_success:
- sh ./bin/deploy.sh
env:
  global:
  - secure: vdxRzke1fxbx7+yvKRYa4psM68GXP/QZjyz4Y6iufOQTJKMnSRzYaPsekFte3wc7WjpZNpXBOVliUrLORpUHihcrYbhpYi/PGJUu2emIdjdCKJ4v1F27qHkx+he4EaDgodq7ItimDMM9Joy7PN/AuufqKbTajarWLTAwzoDa5oDCRM6jNKsYaiQEsUWApCxRZgld+PRbqQ3qlEd7z4QypG+ULyljfHPy8Z1mVNKYv0/TaZqogGK39v2iRwyUXX1mgLE8CN9qdm/aS2rOBedIY7zosamSRraslJOdzx50xYnESzIvSQksDwZlocD4JENAGeA+0/MKToZ0cxTGXCF0CcJEehqpkE49qWG4cNLLE/jPQ0vj/bnyH/5EokUlsTm+SAIncsR810wm9oy7FLJ134uUX5SHEsVdieFM+mK7UyA/N8wBBd+BLA/7w3Ns9GgXLXm6NObdZRDxwxvPLl3nUMGEcBK9lIQIgRzHVSEtxmEbvbbcOXKsvdvJlzP4VFbgFkAl4alYFHbxxAMFnG8g59DUI/8sbgehpiVIkudtAOiHtoc8dyft/Is45KSXA7+bJhMFaa6l/tw8kTMCHfIYi7T0stbuVZzHfRspKbtDyjlcJ7m19OUSflzjbEUXx2N95o2W7WCqtl8pRy0BijUojOuJXZ2Ssh4eh9/qCbejtIM=
  - secure: KlY5RHNSwHaMp5gQf29H9E+xQdvS79+/MTEmABYSxRlc3qSa6IZlHQi+QnNiN/SqLwdzTaIoLbyjlulpoowCvcZxWCVRhCu/x1bQNMsZhUsp87/RaWrH7Yy6jx1R+WT2PqL8JiYBu79o9Vs0sdb86px2cfr6iIWiQRDB+FI0SDbrBdn27pNjSeTQ7cqdWUzOXF1UqdIKXPrpWCUyT4Unbm3Mnhb91NNY5n6DVhc/Fq134v+j/7rAZyXDM52jSmCoFoKUktgc/plwK3O+uMS6EFcm795d/bVt9kb9Ipwz79pfhjs95OcQowN/6G8V3FrOtpmsNQQJHTasCTN6zjO12i+lYmBbGPimo5bqP7Z08CoRuYFQb86k62w68SRfUlHILwp0EvWvD2BlTzKQwMUEQbIOPewG2UrqKrnjRgMHzvNYNzWaw1R8L9Dm8XkrEyrJ2cIG5QtzjK+iPE8Q0c6zBmMrZpHDolgSkAn62kOatLgA0zfhHlpjafroGVddGHkhEM5lty/18B1PW831CRpyZ4DBUtlalp7cgUMG3Bm4b1VXhF2lH6ts9kQAtIEH4W9CWVZL7Y7q7YlTU7Igy0lYUJjjtnnFbL9ld9JkxmR0ob1F9X9NUVfgSeXvbPdPJ66VZZ3qaoeFj3YkWe8uTR85oYaCctJcI3UYZ8MKHz1BGVQ=
  - secure: TnWB++/XG8YDMcoscmtp9+EySiWdQcgSWKrPIv2at0sWcrgwWP3XRnOl1bJrGbl5hhz0LAhxrbgObrn46bqHwF5RtMiq2sKrJ2TNVvRJWWL5P9AKKuS4MMYKmjRxhICJS3M12CDzOQZww+hTXJlldx/5Dq9xSU/s2gcLxOunlNnreKIALVf/G1jSVIJYUvdFhFkJAgKugMqzFumxaHbvAOxxevieHYBLbC3b5laOn+vz/qEicvXcYtRxJXIAwSQMCf3+dAWg/sQQgKTIXzcf4CfuyiFJmkyH5jl+yLrvM2OhqIL5FDCWXN30okrnXeuJhVHA/JYh5cPIymXtgZGWOKUf0LfgZzQAJUgr3jFsEGAcc6f1hwW+pv/Br2L7JX8HEZwqiRiM/z2fxfX29vz2KnYDZhDZx8sz00KlCrSOTEXL42DzvqkvtsPKYjsPT0zqUe/ORls22Nvue9KKDzmVHOzMViGra72BmEw7VrctZFe5RMfgrDqBQVNEzed4lObgK+b7RNuQ2CH7fLKpwx6x4LWqg4wmUTUt+12U7y6cViL4azKAj0NrvsSqZqz12cNLGnPkTnHj+NKLZJDrV/B+V5cVpNIEh19SXknjbaJUmTrJNqXGRZaXxA4aPq0pU7fCPAk7lfAtgp4nfDvGb4Xn3vICXDckuxhs32q1M9f1d60=
notifications:
  slack:
    rooms:
      secure: zoSBxJ+RaEpEBzQDWS/S26+l8ky1I0OHfr9RZSHWelLb+w/MM4PWE/kfHw2sCZK93ShHSOpPxh2FTjFwY7kgQLDKUogTZXhMTLza96r59o9cTl5fcsi8zFk4S0FryloPbN8K2YeSmNaUzK6WnsaPtyZMAAxP+bkWnq1aNxMYKm83qpGw1nWLXLd9kkRS/a0cIg0SLHpmZZkdHMtZb5rGp+ZahdEWzMRDjg6i2MGMlXkw0tIUx8CtC1mUQAQhC5EIz83XTwBowfSS8lAV7r8aN/7pTFEe2uAOTZchvvoygL5NENjh2+6cD8MNPt83EyKdpaYV85/8/ushNbP+AlhOK+V2/lSHPFmtRf9gw4Zsy+fesABop0wU86llIajxUC2JpQP2vDB+YUZtUnXneKjI+AODvLDbvp48XcSPHUlfXJsd+wy3ZbEE33WStkNbmy2TVYqvYfCU0ScV0wxdgbrIV7+9Up2rudJfEFaMwXkWwH5TE+cmq+8iceVEAvBcVtJGgjElUSfDNVEjig/6jyQLueAKSGYeaREoKwrWOrk2GeY9V/qQAK7U9dYYggRKvLlFbX77gO61LTnGdT3WCAOwbz96YKJSgcXDOgcYJN6qO2/D9wpgKOGQM9XRv3DPZLrhVc6hGJ6l0LlI78JV3WHXlX/E87KLBHDGD5LLsSEWrM8=
    template: 
      - "Build %{build_url}#%{build_number} end"
    on_success: always
    on_failure: always
