language: node_js
node_js:
  - '6'
os:
  - linux
git:
  depth: 3
branches:
  only:
    - master
    - develop
before_install:
  - openssl aes-256-cbc -K $encrypted_22aa0a535020_key -iv $encrypted_22aa0a535020_iv -in .env.yml.enc -out .env.yml -d
install:
  - yarn global add serverless
  - yarn install
script:
  - npm run test
after_success:
  - sh ./bin/deploy.sh
