service: foreign-currency-trade
frameworkVersion: ">=1.2.5 <2.0.0"
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    DEBUG: "*"
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: true

plugins:
  - serverless-plugin-chrome
  - serverless-offline
  - serverless-offline-scheduler

custom:
  chrome:
    flags:
      - --window-size=1280x1696 # Letter size
      - --hide-scrollbars
  dotenv:
    - ${file: .env.yml}
functions:
  cron:
    handler: src/handlers/cron.runCron
    environment: ${file(.env.yml)}
    description: Serverless cron
    events:
#      - schedule: rate(5 minutes)
      - schedule: rate(1 minute)

  express:
    handler: src/handlers/test.main
    description: test handler serverless-express
    events:
      - http:
          method: get
          path: '{proxy+}'

  version-info:
    description: Headless Chrome Serverless-framework version info example
    memorySize: 1024
    timeout: 30
    handler: src/handlers/index.default
    events:
      - http:
          path: version-info
          method: get
resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"
