service: foreign-currency-trade
frameworkVersion: ">=1.2.5 <2.0.0"
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment: ${file(.env.yml)}

plugins:
  - serverless-plugin-chrome
  - serverless-offline
  - serverless-offline-scheduler

custom:
  chrome:
    flags:
      - --window-size=1280x1696 # Letter size
      - --hide-scrollbars
functions:
  headless-chrome-example:
    description: Headless Chrome Serverless-framework version info example
    memorySize: 1024
    timeout: 30
    handler: src/handlers/index.default
    events:
      - http:
          path: version-info
          method: get

  scheduled-event-example:
    handler: src/handlers/cron.runCron
    description: Serverless cron
    events:
      - schedule: rate(5 minutes)

  currency-transaction:
    description: Foreign-currency tx request handler
    handler: src/handlers/transaction.main
    events:
      - http:
          method: ANY
          path: '{proxy+}'

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"
