---

service: foreign-currency-trade

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.2.5 <2.0.0"
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 1024
  timeout: 30
  environment:
    DEBUG: "*"
plugins:
  - serverless-plugin-chrome
  - serverless-webpack
custom:
  chrome:
    flags:
      - --window-size=1280x1696 # Letter size
      - --hide-scrollbars
functions:
  version-info:
    description: Version info
    handler: src/handlers/index.handler
    events:
      - http:
          path: version-info
          method: get

...
